
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse.collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.php"><span><?=$info['nama_yayasan'];?></span></a>
      </div>
      <div class="navbar-collapse collapse">
        <div class="menu">
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="<?php if($pageindex){ echo"active";}?>"><a href="index.php">Beranda</a></li>
            <li role="presentation" class="<?php if($pageberita){ echo"active";}?>"><a href="berita.php">Kegiatan</a></li>
            <li role="presentation" class="<?php if($pagekalkulator){ echo"active";}?>"><a href="zakat.php">Kalkulator Zakat</a></li>
            <?php if(!$sudahlogin){?><li role="presentation" > <a href="#" data-toggle="modal" data-target="#login">Masuk</a></li><?php }else{ ?><li role="presentation" > <a href="admin">Halaman Admin</a></li><?php } ?>
          </ul>
        </div>
      </div>
    </div>
  </nav>