    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.php">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"><?=$info['nama_yayasan'];?> <sup></sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item <?php if($dashboard){ echo"active";}?>">
        <a class="nav-link" href="index.php">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      <li class="nav-item <?php if($anaks){ echo"active";}?>">
        <a class="nav-link" href="anak.php">
          <i class="fas fa-fw fa-laugh-wink"></i>
          <span>Data Anak</span></a>
      </li>
      <li class="nav-item <?php if($donasi){ echo"active";}?>">
        <a class="nav-link" href="donasi.php">
          <i class="fas fa-fw fa-dollar-sign"></i>
          <span>Data Donasi</span></a>
      </li>
      <li class="nav-item <?php if($donaturs){ echo"active";}?>">
        <a class="nav-link" href="donatur.php">
          <i class="fas fa-fw fa-user"></i>
          <span>Data Donatur</span></a>
      </li>
      <li class="nav-item <?php if($berita){ echo"active";}?>">
        <a class="nav-link" href="berita.php">
          <i class="fas fa-fw fa-copy"></i>
          <span>Berita</span></a>
      </li>
      <li class="nav-item <?php if($idpetugas){ echo"active";}?>">
        <a class="nav-link" href="pengaturan.php">
          <i class="fas fa-fw fa-key"></i>
          <span>Pengaturan</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="logout.php">
          <i class="fas fa-fw fa-plane"></i>
          <span>Keluar</span></a>
      </li>
    </ul>